//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytics.Data.General {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class GA_RequestURIs : global::System.Configuration.ApplicationSettingsBase {
        
        private static GA_RequestURIs defaultInstance = ((GA_RequestURIs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GA_RequestURIs())));
        
        public static GA_RequestURIs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.google.com/analytics/feeds/data")]
        public string ReportFeed {
            get {
                return ((string)(this["ReportFeed"]));
            }
            set {
                this["ReportFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.googleapis.com/analytics/v3/management/accounts")]
        public string AccountFeed {
            get {
                return ((string)(this["AccountFeed"]));
            }
            set {
                this["AccountFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.googleapis.com/analytics/v3/management/accounts/~all/webproperties/~a" +
            "ll/profiles")]
        public string PorfileFeed {
            get {
                return ((string)(this["PorfileFeed"]));
            }
            set {
                this["PorfileFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.googleapis.com/analytics/v3/management/segments/")]
        public string SegmentFeed {
            get {
                return ((string)(this["SegmentFeed"]));
            }
            set {
                this["SegmentFeed"] = value;
            }
        }
    }
}
